DROP TABLE
IF
	EXISTS article;
CREATE TABLE article (
	id VARCHAR ( 10 ) NOT NULL PRIMARY KEY,
	NAME VARCHAR ( 20 ) NOT NULL,
	description VARCHAR ( 200 ) NOT NULL,
	price DECIMAL ( 10, 2 ) NOT NULL,
	model VARCHAR ( 10 ),
creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);